TCS_Internship/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^user/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^favicon\.ico$', favicon_view),
]

login/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'login' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for login-page:
    url(r'login$', views.login, name='login'),

    #url for signup-page:
    url(r'signup$', views.signup, name='signup'),

    #url to log in a user:
    url(r'log_req$', views.logInReq, name='login_req'),
    
    #url for create-user:
    url(r'register_user$', views.register, name='register_user'),

    #url for logout:
    url(r'logout$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main' 

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),

    #url for donate:
    url(r'^(?P<book>[\w,\s]+)/donate/$', views.donate, name='donate'),

    #url for donate:
    url(r'^(?P<book>[\w,\s]+)/getbook/$', views.getbook, name='getbook'),

    #url not used:
    url(r'^donate-book/$', views.donatebk,name='donate_book'),

    #url for addbook:
    url(r'^addbook$', views.addbk,name='addbook'),

    #url for search:
    url(r'^search$', views.search, name='search'),

    #url for search:
    url(r'^confirm$', views.confirm, name='confirm'),

    #url for search:
    url(r'^orders$', views.orders, name='orders'),

]

main/models.py
from django.db import models
from login.models import User
def rand_key(size):
    return ''.join([random.choice(string.letters + string.digits) for i in range(size)])


class Books(models.Model):
    book_name = models.CharField(max_length=80,unique=True)
    auth_name = models.CharField(max_length=40)
    points = models.IntegerField(default=20)
    price = models.IntegerField(default=0)
    no_of_copies = models.IntegerField(default=0)
    varification = models.BooleanField(default=False)
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.BooleanField()
    def __str__(self):
        return self.book_name

class Order(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    delivered=models.BooleanField(default=False)
    address = models.CharField(max_length=200)

    def __str__(self):
        aii=str(self.auto_increment_id)
        return aii

main/forms.py
from django import forms

class AddBookForm(forms.Form):
    bookname=forms.CharField(max_length = 80)
    auth = forms.CharField(max_length=40)
    price = forms.IntegerField()

main/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse

import re

from login.models import User
from .models import Books,Order
from .forms import AddBookForm

def index(request):
    li=Books.objects.order_by('-pk')[:10]
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=User.objects.get(user_name=uid)
            return render(request, 'Html/index.html',{'usr':user,'list':li})
        except User.DoesNotExist:
            return HttpResponse("UserName not found")
    else:
        return render(request, 'Html/index.html',{'list':li})

def donate(request,book):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=User.objects.get(user_name=uid)
            bk=Books.objects.get(book_name=book)
            bk.no_of_copies+=1
            pts=bk.points
            bk.save()
            user.points+=pts
            user.save()
            li=Books.objects.order_by('-pk')[:10]
            return render(request, 'Html/donate.html',{'usr':user,'list':li,'book':book})
        except (User.DoesNotExist , Books.DoesNotExist):
            return HttpResponse('Book or user does not exist')
    else:
        return HttpResponseRedirect(reverse('login:login'))


def getbook(request,book):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=User.objects.get(user_name=uid)
            bk=Books.objects.get(book_name=book)

            return render(request, 'Html/confirmord.html',{'usr':user,'book':bk})
        except (User.DoesNotExist , Books.DoesNotExist):
            return HttpResponse('Book or user does not exist')
    else:
        return HttpResponseRedirect(reverse('login:login'))


def donatebk(request):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=User.objects.get(user_name=uid)
            if request.method == 'POST':
                bk_nm = request.POST['bookname'] 
                try:
                    book=Books.objects.get(book_name=bk_nm)
                    return render(request, 'Html/donate.html', {'usr':user,'book':book})
                except Books.DoesNotExist:
                    return render(request, 'Html/donate.html', {'usr':user,'book':"notyet"})
        except User.DoesNotExist:
            return HttpResponse('UserName not found')
    else:
        return HttpResponseRedirect(reverse('login:login'))


def addbk(request):
    if request.method == 'POST':
        book=AddBookForm(request.POST)
        if book.is_valid():
            price=int(book.cleaned_data.get('price'))
            points=int(price/10)
            p=Books(book_name=book.cleaned_data.get('bookname'),auth_name=book.cleaned_data.get('auth'),points=points,price=price,varification=False)
            p.save()
    
    return HttpResponseRedirect(reverse('main:index'))

def search(request):
    if request.method == 'POST':
        search=request.POST['search']
        #t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))
        book_li = Books.objects.all()
        li=[]
        for b in book_li:
            if re.search(search,b.book_name,re.IGNORECASE):
                li.append(b)
            elif re.search(search,b.auth_name,re.IGNORECASE):
                li.append(b)
        if request.session.has_key('user_id'):
            uid = request.session['user_id']
            user = User.objects.get(user_name=uid)
            return render(request, 'Html/searchresults.html', {'user_id':user,"list": li})
        else:
            return render(request, 'Html/searchresults.html', {"list": li})
    else:
        return HttpResponse("not POST")

def confirm(request):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        book=request.POST['book']
        address=request.POST['add']
        try:
            user=User.objects.get(user_name=uid)
            bk=Books.objects.get(book_name=book)
            if bk.no_of_copies==0:
                return HttpResponse('The book'+book+'is out of stock')
            bk.no_of_copies-=1
            pts=bk.points
            if user.points<pts:
                return HttpResponse("You don't have the required pts")
            bk.save()
            user.points-=pts
            user.save()
            if address=="":
                address=user.address
            order=Order(user=user,book=bk,delivered=False,address=address)
            order.save()
            li=Books.objects.order_by('-pk')[:10]
            return render(request, 'Html/getbook.html',{'usr':user,'list':li,'book':book})
        except (User.DoesNotExist , Books.DoesNotExist):
            return HttpResponse('Book or user does not exist')
    else:
        return HttpResponseRedirect(reverse('login:login'))

def orders(request):
    if request.session.has_key('user_id'):
        uid=request.session['user_id']
        try:
            user=User.objects.get(user_name=uid)
            li=Order.objects.filter(user=user)
            return render(request, 'Html/orders.html',{'list':li,'usr':user})
        except (User.DoesNotExist , Books.DoesNotExist):
            return HttpResponse('Book or user does not exist')

    else:
        return HttpResponseRedirect(reverse('login:login'))

main/templates/Html/donate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>ReadersStop</title>
		<meta name="generator" content="Bootply" />
		
        {% load staticfiles %}
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/gif" sizes="16x16">
        <link rel="stylesheet" type="text/css" href="{% static '/main/book_card.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/main/search.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/main/donate.css' %}"/>


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="icon" href="favicon.ico" type="image/gif" sizes="16x16">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.form/4.2.1/jquery.form.min.js" integrity="sha384-tIwI8+qJdZBtYYCKwRkjxBGQVZS3gGozr3CtI+5JF/oL1JmPEHzCEnIKbDbLTCer" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

        <script src="https://use.fontawesome.com/b37c191d35.js"></script>
		
	</head>
    <body style="background-color: #4c8eaf;">

     <div id="received"><p style="color: #ffffff" >Your book: <strong>{{ book }}</strong> has been received !<br></div>
       
<!-- ===================================HEADER========================================================== -->

        <nav class = "navbar navbar-default navbar-fixed-top" style = "background-color:rgb(81, 152, 106)">
    <div class="container" id = "navFluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar" style="color: white; background-color: white"></span>
          <span class="icon-bar" style="color: white;background-color: white"></span>
          <span class="icon-bar" style="color: white;background-color: white"></span> 
        </button>
        <a class="navbar-brand" href="/" style = "background-color:rgb(81, 152, 106); display:flex;padding:12px 15px;align-items:center; "><img src="{% static 'images/header_icon.png' %}" style="height: 300%"></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar" style = "background-color:rgb(81, 152, 106)">
        <ul class="nav navbar-nav">
          <li style="font-size:20px"><a href="/" style="color: white"><strong>Reader's Stop</strong></a></li> 
        </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if usr %}

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white"> {{ usr.user_name }} <span class="glyphicon glyphicon-option-horizontal"></span></a>
          <ul style="text-align:left;" class="dropdown-menu">                 
                          <li><a href="" style="color: black; background-color:#f1f1f1">Your Points:{{ usr.points }}</a></li> 
                          <li><a href="{% url 'main:orders' %}" style="color: black; background-color:#f1f1f1">Your Orders</a></li>  
          </ul>
          </li> 
        <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:logout' %}" style="color: white"> Logout </a></li>
        


        {% else %}
            <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:signup' %}" style="color: white"> Sign Up </a></li>
            <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:login' %}" style="color: white"> Log In </a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>







<!-- ======================================================================================================================= -->



 <div class = "container" class="col-md-12 col-xs-12 col-lg-12 col-sm-12"> 
        <div class="col-md-12 search"> 
        
          
          <div class="col-md-12">
          <form method="POST" action="{% url 'main:search' %}">
            {% csrf_token %}
            <input type="text" class="form-control" id="search" name = "search" placeholder="&#xF002;    Search by Name or Author..."/ style="font-family: FontAwesome"> 

     
          </form>
          </div>
      </div>
      </div>
       
        <!-- {% if usr %}
            <h2> {{ usr.user_name }}</h2>
            <p>Your Points:{{ usr.points }}</p>
            <a href="{% url 'login:logout' %}">Log Out</a>
        {% else %}
            <a href="{% url 'login:signup' %}">Sign Up</a>
            <a href="{% url 'login:login' %}">Log In</a>
        {% endif %}
        <br>
        <form method="POST" action="{% url 'main:search' %}">
            {% csrf_token %}
            <input type="text" placeholder="Name or author name search" name="search">
            <button >search</button>
        </form>    -->


<div class="container">
        <div class = "col-xs-12 col-lg-12 col-sm-12 col-md-12" style="background-color: #f1f1f1; margin-top: 5%">

        <div style="padding: 20px 0">

            {% for i in list %}
          <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4" style="background-color: #f1f1f1; padding: 0px 20px;">
            <div class="categoryWrap" style = "display:flex; align-items:center; flex-direction:column;height:450px">
              <div style = "display:flex; align-items:center">
                <img src = "{% static 'images/book-open-flat.png' %}" class="catImage text-center" style=" margin-top: 20%;width:80px; height:80px; border-radius: 50px;">
              </div>
              <div class="catContent" style = "align-items:center">
                <h3 class="titleHeading" style = "text-align:center"> {{ i.book_name }}
                </h3>
                <p class = "help-block" style = "text-align:center">Author:{{ i.auth_name }}<br> </p>
                <hr>
                <div style="margin-bottom: 10px;">
                  <p style = "text-align:center">Points:{{ i.points }}<br>
                  </p>
                </div>
                <br/>

                {% if i.varification == False %}
                    <p style="color: #de5b5b">* This book's data has not been verified by our admins yet! *</p>

                {% else %}
                <div class="col-md-12">
                    <div class="col-xs-12 col-md-12" style = "align-items:center; text-align:center;"><br>
                    <a href="{% url 'main:donate' i.book_name %}" class="btn btn-info btnBg" style = "background-color: #de5b5b; border-color: #de5b5b">
                        <span >Donate book</span> 
                    </a>
                    </div>

                    <div class="col-xs-12 col-md-12" style = "align-items:center; text-align:center; "><br>
                    <a href="{% url 'main:getbook' i.book_name %}" class="btn btn-info btnBg" style = "background-color: #5bde95; border-color: #5bde95">
                        <span>Get book</span> 
                    </a>
                    </div>
                </div>
                {% endif %}


              </div>
              <div class="cl">
              </div>
              <br/>
            </div>
            <div class="cl">
            </div>
            <br/>
            <br/>
          </div>
            {% endfor %}
        </div>
      </div>
    </div> 
    </div>

  <!--      {% for i in list %}
                <p>
                Book Name:{{ i.book_name }}<br>
                Author:{{ i.auth_name }}<br>
                Points:{{ i.points }}<br>
                
                
                {% if i.varification == False %}
                    This book's data has not been varified by our admins yet!
                {% else %}
                    <a href="{% url 'main:donate' i.book_name %}">Donate this book</a>
                    <a href="{% url 'main:getbook' i.book_name %}">Get this book</a>
                {% endif %}
                </p>
        {% endfor %}     -->


<!-- ======================================FOOTER============================================ -->
<link rel="stylesheet" type="text/css" href="{% static '/main/footer.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="dashboard-page">

    <div class='footer' style="margin-top: 10%;">
 <div class='container'>
   <div class='row'>

     <div class='clearfix visible-xs'></div>

     


    <div class='col-sm-12 col-md-12 col-xs-12' style="text-align: center; align-items: center;">
      

      <h4>CONTACT US</h4>
      <h5 style="color:#ED5E44;">+91 9999688904</h5>
      <h5 style="color:#ED5E44;">help_readers@gmail.com</h5>
   
    </div>

  </div>

  

  </div>
  <div class="sec-footer">
       <div style="display:flex; justify-content:center;align-items:center;">
           
           <img style="padding:0 20px; height: 50px;" src="{% static 'images/footer_logo.png' %}">
     </div>
  </div>
  <div style="text-align:center;background-color:#252525; height:60px;padding-top: 10px">
  <div class="sec-content" style="display: inline">
        &copy; 2017 Reader's Stop
        <p>Made with <i class="fa fa-heart" aria-hidden="true"></i> at TCS.
      </div> 

    </div>
</div> 
</div> 
<!-- ================================================================= -->
</body>
</html>

main/templates/Html/searchresults.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta name="fragment" content="!">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
        <title>ReadersStop</title>
		
        <meta name="generator" content="Bootply" />

        {% load staticfiles %}
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/gif" sizes="16x16">
        <link rel="stylesheet" type="text/css" href="{% static '/main/book_card.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/main/search.css' %}"/>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="icon" href="favicon.ico" type="image/gif" sizes="16x16">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.form/4.2.1/jquery.form.min.js" integrity="sha384-tIwI8+qJdZBtYYCKwRkjxBGQVZS3gGozr3CtI+5JF/oL1JmPEHzCEnIKbDbLTCer" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

        <script src="https://use.fontawesome.com/b37c191d35.js"></script>
		
	</head>
	<body style="background-color: #4c8eaf;">

	
<!-- ===================================HEADER========================================================== -->

        <nav class = "navbar navbar-default navbar-fixed-top" style = "background-color:rgb(81, 152, 106)">
    <div class="container" id = "navFluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar" style="color: white; background-color: white"></span>
          <span class="icon-bar" style="color: white;background-color: white"></span>
          <span class="icon-bar" style="color: white;background-color: white"></span> 
        </button>
        <a class="navbar-brand" href="/" style = "background-color:rgb(81, 152, 106); display:flex;padding:12px 15px;align-items:center; "><img src="{% static 'images/header_icon.png' %}" style="height: 300%"></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar" style = "background-color:rgb(81, 152, 106)">
        <ul class="nav navbar-nav">
          <li style="font-size:20px"><a href="/" style="color: white"><strong>Reader's Stop</strong></a></li> 
        </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if usr %}

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white"> {{ usr.user_name }} <span class="glyphicon glyphicon-option-horizontal"></span></a>
          <ul style="text-align:left;" class="dropdown-menu">                 
                          <li><a href="" style="color: black; background-color:#f1f1f1">Your Points:{{ usr.points }}</a></li> 
                          <li><a href="{% url 'main:orders' %}" style="color: black; background-color:#f1f1f1">Your Orders</a></li>  
          </ul>
          </li> 
        <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:logout' %}" style="color: white"> Logout </a></li>
        


        {% else %}
            <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:signup' %}" style="color: white"> Sign Up </a></li>
            <li style = "background-color:rgb(81, 152, 106);"><a href="{% url 'login:login' %}" style="color: white"> Log In </a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>







<!-- ======================================================================================================================= -->







        <div class = "container" class="col-md-12 col-xs-12 col-lg-12 col-sm-12"> 
        <div class="col-md-12 search"> 
        
          
          <div class="col-md-12">
          <form method="POST" action="{% url 'main:search' %}">
            {% csrf_token %}
            <input type="text" class="form-control" id="search" name = "search" placeholder="&#xF002;    Search by Name or Author..."/ style="font-family: FontAwesome"> 

     
          </form>
          </div>
      </div>
      </div>
        

<div class="container">
        <div class = "col-xs-12 col-lg-12 col-sm-12 col-md-12" style="background-color: #f1f1f1; margin-top: 5%">

        <div style="padding: 20px 0">
        {% if list %}
            {% for i in list %}
          <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4" style="background-color: #f1f1f1; padding: 0px 20px;">
            <div class="categoryWrap" style = "display:flex; align-items:center; flex-direction:column;height:450px">
              <div style = "display:flex; align-items:center">
                <img src = "{% static 'images/book-open-flat.png' %}" class="catImage text-center" style=" margin-top: 20%;width:80px; height:80px; border-radius: 50px;">
              </div>
              <div class="catContent" style = "align-items:center">
                <h3 class="titleHeading" style = "text-align:center"> {{ i.book_name }}
                </h3>
                <p class = "help-block" style = "text-align:center">Author:{{ i.auth_name }}<br> </p>
                <hr>
                <div style="margin-bottom: 10px;">
                  <p style = "text-align:center">Points:{{ i.points }}<br>
                  </p>
                </div>
                <br/>

                {% if i.varification == False %}
                    <p style="color: #de5b5b">* This book's data has not been verified by our admins yet! *</p>

                {% else %}
                <div class="col-md-12">
                    <div class="col-xs-12 col-md-12" style = "align-items:center; text-align:center;"><br>
                    <a href="{% url 'main:donate' i.book_name %}" class="btn btn-info btnBg" style = "background-color: #de5b5b; border-color: #de5b5b">
                        <span ">Donate book</span> 
                    </a>
                    </div>

                    <div class="col-xs-12 col-md-12" style = "align-items:center; text-align:center; "><br>
                    <a href="{% url 'main:getbook' i.book_name %}" class="btn btn-info btnBg" style = "background-color: #5bde95; border-color: #5bde95">
                        <span>Get book</span> 
                    </a>
                    </div>
                </div>
                {% endif %}


              </div>
              <div class="cl">
              </div>
              <br/>
            </div>
            <div class="cl">
            </div>
            <br/>
            <br/>
          </div>
            {% endfor %}
        </div>
      </div>
    </div> 


        <div class = "container" class="col-md-12 col-xs-12 col-lg-12 col-sm-12"> 
        <div class="col-md-12 search"> 
        
          
        <div class="col-md-12">
        {% else %}
            <h3> This book is not one of the pre-existing books in our database. Please give details of this book to add it to our database.</h3>
            
            <form style="padding-top:20px"method="POST" action="{% url 'main:addbook' %}">
			{% csrf_token %} 
              <div class="form-group">
                <input class="form-control" type="text" name="bookname" placeholder="Book Name">
              </div>
              <div class="form-group">
                <input class="form-control" type="text" name="auth" placeholder="Author" required>
			        </div>
              <div class="form-group">
                <input class="form-control" type="text" name="price" placeholder="Original Price in Rupees" required>
              </div>
              <button id="button">Add Book</button>
            </form>
        {% endif %}
        </div>
        </div>
        </div>




<!--================-->
<link rel="stylesheet" type="text/css" href="{% static '/main/footer.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="dashboard-page">

    <div class='footer' style="margin-top: 10%;">
 <div class='container'>
   <div class='row'>

     <div class='clearfix visible-xs'></div>

     


    <div class='col-sm-12 col-md-12 col-xs-12' style="text-align: center; align-items: center;">
      

      <h4>CONTACT US</h4>
      <h5 style="color:#ED5E44;">+91 9999688904</h5>
      <h5 style="color:#ED5E44;">help_readers@gmail.com</h5>
   
    </div>

  </div>

  

  </div>
  <div class="sec-footer">
       <div style="display:flex; justify-content:center;align-items:center;">
           
           <img style="padding:0 20px; height: 50px;" src="{% static 'images/footer_logo.png' %}">
     </div>
  </div>
  <div style="text-align:center;background-color:#252525; height:60px;padding-top: 10px">
  <div class="sec-content" style="display: inline">
        &copy; 2017 Reader's Stop
        <p>Made with <i class="fa fa-heart" aria-hidden="true"></i> at TCS.
      </div> 

    </div>
</div> 
</div> 
<!-- ================================================================= -->


        
</body>
</html>