TCS_Internship/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^user/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^favicon\.ico$', favicon_view),
]

login/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'login' 
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for login-page:
    url(r'login$', views.login, name='login'),

    #url for signup-page:
    url(r'signup$', views.signup, name='signup'),

    #url to log in a user:
    url(r'log_req$', views.logInReq, name='login_req'),
    
    #url for create-user:
    url(r'register_user$', views.register, name='register_user'),

    #url for logout:
    url(r'logout$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main' 

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),

    #url for donate:
    url(r'^(?P<book>[\w,\s]+)/donate/$', views.donate, name='donate'),

    #url for donate:
    url(r'^(?P<book>[\w,\s]+)/getbook/$', views.getbook, name='getbook'),

    #url not used:
    url(r'^donate-book/$', views.donatebk,name='donate_book'),

    #url for addbook:
    url(r'^addbook$', views.addbk,name='addbook'),

    #url for search:
    url(r'^search$', views.search, name='search'),

    #url for search:
    url(r'^confirm$', views.confirm, name='confirm'),

    #url for search:
    url(r'^orders$', views.orders, name='orders'),

]

login/models.py
from django.db import models

class User(models.Model):
    user_name = models.CharField(max_length=80,unique=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=120)
    pwd= models.CharField(max_length=32)
    points= models.IntegerField(default=0)
    address = models.CharField(max_length=200)
    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.BooleanField()
    def __str__(self):
        return self.user_name

login/forms.py
from django import forms

class SignupForm(forms.Form):
    username=forms.CharField(max_length = 80)
    firstname = forms.CharField(max_length=30)
    lastname = forms.CharField(max_length=30)
    email = forms.CharField(max_length=120)
    pwd= forms.CharField(max_length=80)

class LoginForm(forms.Form):
    username=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

login/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse
#for older versoins of Django use:
#from django.core.urlresolvers import reverse

from .models import User
from .forms import SignupForm,LoginForm

def login(request):
    return render(request, 'Html/login.html')
def signup(request):
    return render(request, 'Html/signup.html')

def register(request):
    if request.method == 'POST':
        signup=SignupForm(request.POST)
        if signup.is_valid():
            p=User(user_name=signup.cleaned_data.get('username'),first_name=signup.cleaned_data.get('firstname'),last_name=signup.cleaned_data.get('lastname'),email=signup.cleaned_data.get('email'),pwd=signup.cleaned_data.get('pwd'))
            p.save()
    request.session['user_id'] = p.user_name
    return HttpResponseRedirect(reverse('main:index'))

def logInReq(request):
    if request.method == 'POST':
        log=LoginForm(request.POST)
        if log.is_valid():
            try:
                user=User.objects.get(user_name=log.cleaned_data.get('username'),pwd=log.cleaned_data.get('pwd'))
                request.session['user_id'] = user.user_name
                return HttpResponseRedirect(reverse('main:index'))
            except User.DoesNotExist:
                return HttpResponse("WRONG USERNAME OR PASSWORD")

def logout(request):
   try:
      del request.session['user_id']
   except:
      pass
   return HttpResponseRedirect(reverse('main:index'))

login/templates/Html/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ReadersStop</title>
	<meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <title>{% block title %}Viberr{% endblock %}</title> -->
    {% load staticfiles %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/gif" sizes="16x16">
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'login/base.css' %}"/>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/gif" sizes="16x16">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.form/4.2.1/jquery.form.min.js" integrity="sha384-tIwI8+qJdZBtYYCKwRkjxBGQVZS3gGozr3CtI+5JF/oL1JmPEHzCEnIKbDbLTCer" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body style="background-color: #4c8eaf;">


<div class="container" id="main_form" style="margin-top: 5%;">  

  <div id="contact" style="margin-top: 30%; margin-bottom: 0%">
    <h3>Login !</h3>
    <h4>Enter Your Credentials</h4>
    
    <form id = "myForm" action="{% url 'login:login_req' %}" method="post">
    {% csrf_token %} 

    <fieldset>
      <input placeholder="Username" type="text" tabindex="1" required autofocus name="username" style="width: 100%;">
    </fieldset>
    <fieldset>
      <input placeholder="Password" type="password" tabindex="2" required name="pwd" style="width: 100%; padding-left: 10px">
    </fieldset>
    
      <button name="submit" type="submit" id="contact-submit">Sign In</button>    
  </form>
</div>
</body>
</html>

login/templates/Html/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ReadersStop</title>
	<meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <title>{% block title %}Viberr{% endblock %}</title> -->
    {% load staticfiles %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/gif" sizes="16x16">
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'login/base.css' %}"/>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/gif" sizes="16x16">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.form/4.2.1/jquery.form.min.js" integrity="sha384-tIwI8+qJdZBtYYCKwRkjxBGQVZS3gGozr3CtI+5JF/oL1JmPEHzCEnIKbDbLTCer" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body style="background-color: #4c8eaf;">


<div class="container" id="main_form" style="margin-top: 5%;margin-bottom: 5%;">  

  <div id="contact" style="margin-top: 30%; margin-bottom: 0%">
    <h3>Sign Up !</h3>
    <h4>Enter the aforementioned details</h4>
    
    <form method="POST" action="{% url 'login:register_user' %}">
		{% csrf_token %} 
		<fieldset>
      		<input placeholder="Username" type="text" tabindex="1" required autofocus name="username" style="width: 100%;">
    	</fieldset>


    	<fieldset>
	    	<input placeholder="First Name" type="text" tabindex="1" required autofocus name="firstname" style="width: 100%;">
	    </fieldset>

    	<fieldset>
      		<input placeholder="Last Name" type="text" tabindex="1" required autofocus name="lastname" style="width: 100%;">
    	</fieldset>

      <fieldset>
          <input placeholder="Address" type="text" tabindex="1" required autofocus name="address" style="width: 100%;">
      </fieldset>

    	<fieldset>
      		<input placeholder="Email" type="email" tabindex="1" required autofocus name="email" style="width: 100%;">
    	</fieldset>

    	<fieldset>
      		<input placeholder="Password" type="password" tabindex="1" required autofocus name="pwd" style="width: 100%; padding-left: 10px;">
    	</fieldset>

    	<fieldset>
      		<input placeholder="Confirm Password" type="password" tabindex="1" required autofocus name="pwd2" style="width: 100%;padding-left: 10px;">
    	</fieldset>


    
      <button name="submit" type="submit" id="contact-submit" style="margin-top: 10%;">Sign Up</button>    
  </form>
</div>
</body>
</html>